CREATE OR REPLACE PROCEDURE GET_TABLE_LIST_03(
    R_ID OUT VARCHAR2,
    R_NAME OUT VARCHAR2,
    R_EMAIL OUT VARCHAR2
) IS
    CURSOR P_CURSOR IS
        SELECT
            *
        FROM
            TEST01_USERS;
 --- レコード
    TEST01_USERS_REC P_CURSOR%ROWTYPE;
BEGIN
    OPEN P_CURSOR;
    FETCH P_CURSOR INTO TEST01_USERS_REC;
    CLOSE P_CURSOR;
 --- カラムの値を挿入
    R_ID := TEST01_USERS_REC.ID; -- .カラム名
    R_NAME := TEST01_USERS_REC.NAME; --- .カラム名
    R_EMAIL := TEST01_USERS_REC.EMAIL; --- .カラム名
END;